Repository Qovery/engine, pull requests merged in 2020-12, with the labels that each got.

#51 feat: adding documentdb 4
  tests/aws/aws_databases.rs
Labels: full-tests

#63 feat: adding gh action automerge like gitlab
  .github/workflows/functionnal_tests.yml
Labels: merge_when_pipeline_succeeds

#60 feat: adding externaldns support for DO
  Cargo.lock
  lib/digitalocean/bootstrap/chart_values/external-dns.j2.yaml
  lib/digitalocean/bootstrap/doks-gen-kubectl-config.j2.tf
  lib/digitalocean/bootstrap/helm-external-dns.tf
  src/cloud_provider/aws/kubernetes/mod.rs
  src/cloud_provider/digitalocean/application.rs
  src/cloud_provider/digitalocean/databases/postgresql.rs
  src/cloud_provider/digitalocean/kubernetes/mod.rs
  tests/assets/do-options.json
  tests/digitalocean/do_container_registry.rs
  tests/digitalocean/do_databases.rs
  tests/digitalocean/do_environment.rs
  tests/digitalocean/do_kubernetes.rs
  tests/digitalocean/mod.rs
Labels: merge_when_pipeline_succeeds

#71 fix: delete environment resources order (swap stateful with stateless)
  src/cloud_provider/aws/kubernetes/mod.rs
Labels: full-tests, merge_when_pipeline_succeeds

#89 fix: better support of database versions
  src/cloud_provider/aws/databases/mongodb.rs
  src/cloud_provider/aws/databases/mysql.rs
  src/cloud_provider/aws/databases/postgresql.rs
  src/cloud_provider/aws/databases/redis.rs
  src/cloud_provider/aws/databases/utilities.rs
  tests/aws/aws_databases.rs
Labels: merge_when_pipeline_succeeds

#96 fix: build cache
  src/build_platform/mod.rs
  src/cloud_provider/aws/application.rs
  src/cloud_provider/aws/kubernetes/mod.rs
  src/transaction.rs
Labels: merge_when_pipeline_succeeds

#97 fix: update tfstate name on services to avoid name collision
  lib/aws/services/common/backend.j2.tf
  src/cloud_provider/aws/databases/mongodb.rs
  src/cloud_provider/aws/databases/mysql.rs
  src/cloud_provider/aws/databases/postgresql.rs
  src/cloud_provider/aws/databases/redis.rs
  src/cloud_provider/aws/databases/utilities.rs
  src/cmd/kubectl.rs
Labels: full-tests

#100 fix: show k8s events on deployment error
  src/build_platform/local_docker.rs
  src/cloud_provider/aws/application.rs
  src/cloud_provider/aws/common.rs
  src/cloud_provider/aws/databases/mod.rs
  src/cloud_provider/kubernetes.rs
  src/cmd/kubectl.rs
  src/cmd/structs.rs
Labels: merge_when_pipeline_succeeds
