Repository Qovery/engine, pull requests merged in 2021-01, with the labels that each got.

#111 fix: better support of log output depending of running on CI or not
  test_utilities/src/utilities.rs
Labels: ready to merge

#110 feat: force cert-manager to use specific DNS to speed up resolution
  lib/aws/bootstrap/helm-cert-manager.j2.tf
  lib/digitalocean/bootstrap/helm-cert-manager.j2.tf
Labels: ready to merge

#120 feat: adding autoscaler
  Cargo.lock
  lib/aws/bootstrap/eks-workers-nodes.j2.tf
  lib/aws/bootstrap/helm-alertmanager-discord.tf
  lib/aws/bootstrap/helm-aws-limits-exporter.tf
  lib/aws/bootstrap/helm-aws-node-term-handler.tf
  lib/aws/bootstrap/helm-cert-manager.j2.tf
  lib/aws/bootstrap/helm-cluster-autoscaler.tf
  lib/aws/bootstrap/helm-external-dns.tf
  lib/aws/bootstrap/helm-grafana.tf
  lib/aws/bootstrap/helm-loki.tf
  lib/aws/bootstrap/helm-metrics-server.tf
  lib/aws/bootstrap/helm-nginx-ingress.tf
  lib/aws/bootstrap/helm-pleco.j2.tf
  lib/aws/bootstrap/helm-prometheus-operator.j2.tf
  lib/aws/bootstrap/helm-qovery-agent.tf
  lib/aws/bootstrap/helm-qovery-engine.tf
  lib/aws/bootstrap/tf-providers-aws.j2.tf
  lib/common/bootstrap/charts/cluster-autoscaler/.helmignore
  lib/common/bootstrap/charts/cluster-autoscaler/Chart.yaml
  lib/common/bootstrap/charts/cluster-autoscaler/README.md
  lib/common/bootstrap/charts/cluster-autoscaler/README.md.gotmpl
  lib/common/bootstrap/charts/cluster-autoscaler/templates/_helpers.tpl
  lib/common/bootstrap/charts/cluster-autoscaler/templates/clusterrole.yaml
  lib/common/bootstrap/charts/cluster-autoscaler/templates/clusterrolebinding.yaml
  lib/common/bootstrap/charts/cluster-autoscaler/templates/deployment.yaml
  lib/common/bootstrap/charts/cluster-autoscaler/templates/pdb.yaml
  lib/common/bootstrap/charts/cluster-autoscaler/templates/podsecuritypolicy.yaml
  lib/common/bootstrap/charts/cluster-autoscaler/templates/priority-expander-configmap.yaml
  lib/common/bootstrap/charts/cluster-autoscaler/templates/role.yaml
  lib/common/bootstrap/charts/cluster-autoscaler/templates/rolebinding.yaml
  lib/common/bootstrap/charts/cluster-autoscaler/templates/secret.yaml
  lib/common/bootstrap/charts/cluster-autoscaler/templates/service.yaml
  lib/common/bootstrap/charts/cluster-autoscaler/templates/serviceaccount.yaml
  lib/common/bootstrap/charts/cluster-autoscaler/templates/servicemonitor.yaml
  lib/common/bootstrap/charts/cluster-autoscaler/values.yaml
  lib/helm-freeze.yaml
  src/cloud_provider/aws/databases/redis.rs
  src/cloud_provider/aws/kubernetes/mod.rs
  src/cloud_provider/digitalocean/kubernetes/mod.rs
  test_utilities/src/aws.rs
  test_utilities/src/digitalocean.rs
Labels: ready to merge

#121 use the new commit for branch mysql
  lib/aws/services/mysql/main.j2.tf
  lib/aws/services/mysql/variables.j2.tf
  lib/aws/services/postgresql/main.j2.tf
  lib/aws/services/postgresql/variables.j2.tf
  src/cloud_provider/aws/databases/mongodb.rs
  src/cloud_provider/aws/databases/mysql.rs
  src/cloud_provider/aws/databases/postgresql.rs
  src/cloud_provider/aws/databases/redis.rs
  src/cloud_provider/kubernetes.rs
  src/cloud_provider/service.rs
  src/cloud_provider/utilities.rs
  tests/aws/aws_databases.rs
Labels: full-tests

#131 feat: adding DO test for custom domain
  src/cloud_provider/digitalocean/models/svc.rs
  src/cmd/kubectl.rs
  test_utilities/src/digitalocean.rs
  tests/digitalocean/do_environment.rs
Labels: full-tests, ready to merge
